tpch:
  target: dev
  outputs:
    dev:
      type: snowflake
      warehouse: DEV_WH
      database: ANALYTICS
      schema: dbt_jtoraason
      role: TRANSFORMER
      threads: 4
    prod:
      type: snowflake
      warehouse: DEV_WH
      database: ANALYTICS
      schema: dbt
      role: ORCHESTRATOR
      threads: 4
